version: "3.8"

services:
  wecare-ecommerce:
    image: wecare-ecommerce:latest
    hostname: wecare.com.vn
    ports:
      - "3000:3000"
    labels:
      NAME: "wecare-ecommerce"
    networks:
      - dev
    restart: always
    volumes:
      - "./public:/app/public"
      - "./src:/app/src"
